### ISSUE TITLE
option to overwrite exisiting BunwarpJ folder

### ISSUE THREAD

**Issue by moenigin** [fmi-basel/neuRoi#12]
Currently it just checks exisitance of a folder and does not allow to overwrite by propmt:
https://github.com/fmi-basel/neuRoi/blob/7df4770ee3fe0f4909ee330ab238037e4ea0bc37/NrModel.m#L1183

Also it is inconvnient that one has to delete "Change transformation name" before bing able to type a name

**Comment by Eggord** [comment]
Yes this is a feature not a bug ;)
You can always delete the folder manually in your experiment folder and the next time you load the experiment the transformation is gone.
With this method, there is a close to 0 chance that you delete a transformation by chance....

**Comment by moenigin** [comment]
Thanks for the fix @aloejhb! 
I think only with this it becomes a feature :-). Since the overwrite dialogue only pops up when a folder already exists and neuROI does not use to many popups, the user should not easily be biased to clicking ok on everything. There is still a chance to acknowledge overwrite accidentally but I'd consider it low. If the folder has to be manually deleted the chance of annoyance is close to 1 :D
