### ISSUE TITLE
using the keyboard to zoom in the BigWarpGui

### ISSUE THREAD

**Issue by moenigin** [fmi-basel/neuRoi#14]
In the Bigwarp GUI zoom in and out via key1/key- or key2/key= is disabled and one has to refer to the standard Matalb GUI tools as for panning. These are super inconvenient because they deselct the current figure and any key input while they are ensabled will be entered in the command line making the figure disappear.

**Comment by Eggord** [comment]
should work now with the normal shortcuts as in the normal trials

**Comment by moenigin** [comment]
Thanks a lot @Eggord!
